[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
for i = 1, 4 do 
    table.sort(self.P_JOKER_RARITY_POOLS[i], function (a, b) return a.order < b.order end)
end
'''
position = "after"
payload = '''
for k,v in pairs(self.P_CENTERS) do
    print(k)
    v.config = v.config or {}
    v.config.fg_data = {
        is_alternate = false,
        alternate_card = string.sub(k,1,1).."_fg_"..string.sub(k,3),
        vars = {}
    }

end
'''
match_indent = false
times = 1
